### ISSUE TITLE
API Usage

### ISSUE THREAD

**Issue by Ganonmaster** [Meshhouse/sfmlab-unofficial-api#1]
Hello,

I'm the site admin of the sites you created this tool for. Can I ask to what purpose you are using this API? I've noticed in the past that scraping/scanning that your tool does, causes unnecessary strain on the site servers.

If you wish to interact with the site programmatically in the future, please contact me directly to work something out, rather than rigging up your own implementation in this manner.

Furthermore, I'm concerned that your tool seems intent on creating unauthorized full data backups of the site, without preserving the license notices and proper attribution. This goes against the hard work that I, and the uploaders put into creating the site and the assets on it.

I hope to hear from you shortly.

**Comment by longsightedfilms** [comment]
Hello, sorry for very late answer (I'm abandoned this project a couple years ago). I'm use Google Translate, because my english not very good.

Initially, I created this project with the goal of providing an API for your site in my application - MeshHouse (it's a 3D model cataloger that I write purely for myself, but then it happened that I posted it on GitHub). One of the goals of my application is to provide a convenient way to manage models from different sources in one place (which I personally used, although I do not use Blender). Yes - I know that Blender seems to have a built-in model organizer, but then again, as I wrote above, my application is DCC agnostic (i.e. does not depend on the editor used).

The scheme of the application was such that I parsed the main page and the page with models, translated it into a convenient format for myself and saved it to my database. All this was done only for several reasons:
1. The absence of any public API
2. Slow loading speed of the site (for obvious reasons)

I want to note that I saved only the information about the model, comments and images - the files themselves were still loaded from your storage. As far as I remember now, I also saved all the licenses installed for each model to myself in order to show them to end users (which does not seem to violate the Creative Commons licenses that are installed for 99% of the models on your site).

I perfectly understand your indignation due to the possible damage from my project, so I am currently closing it (the repository will be archived). The integration of my application with your sites will be redone (if not by me, then by third-party users) - I will provide an API of plugins that allows you to write your own integrations with third-party sites. In this case, all responsibility will lie with the author of the plugin, and not with me.

Thank you for understanding.
